version: '3.1'

services:
    reddit_stats:
        build: ./reddit_stats
        restart: unless-stopped
        depends_on:
          - db 
    charlie:
        build: ./charlie
        restart: unless-stopped
        depends_on:
          - db
    stats_bot:
        build: ./stats_bot
        restart: unless-stopped
        depends_on:
          - db
        environment:
            PYTHONUNBUFFERED: 1
    db:
        image: postgres:9.6
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - "./pg_data:/var/lib/postgresql/data"
